kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoamiapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      name: whoamiapp
      labels:
        app: whoami
        env: dev
    spec:
      containers:
      - name: whoamiapp
        image: {Azure Container Registry link} / {name:tag}
      imagePullSecrets:
      - name: acr-auth
---
kind: Service
apiVersion: v1
metadata:
  name: whoamiapp
  labels:
    name: whoamiapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: whoami